<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Label_sheets</name>
   <tag></tag>
   <elementGuidId>73b60dc0-2718-4bcd-9cd9-df44a3c66219</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//option[contains(@label, 'TimeSeries')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>TimeSeries</value>
   </webElementProperties>
</WebElementEntity>
