<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Aggregation_Method</name>
   <tag></tag>
   <elementGuidId>7087499b-017c-41cc-9f61-53d8a549b921</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(text(),'Aggregate')]/ancestor::div[1]//option[@label=&quot;Calculation&quot;][@selected=&quot;selected&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
