<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_xpath</name>
   <tag></tag>
   <elementGuidId>b0d008f1-51a2-4ff3-abf8-e28cd5801bee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/dw-authoring-datatable-editor2/div[2]/div[2]/dw-authoring-user-defined-column-container/dw-authoring-calculated-column-settings/div/div/div[4]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
